Merge Milestone 3 to Dev branch
MephistoDevelop/tictac pull request #18
Opened 2020-02-20 20:33 UTC by MephistoDevelop

Features Added:
- winning Patern
- Draw Detection
- Restart Game loop

2020-02-21 07:07 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments on your code. 👇 

- [x] When there is a winner or a draw, it is not displaying the winner or informing that it's a draw, it is having the error shown below:
```ruby
bin/main.rb:19:in `<main>': undefined method `winner?' for #<Board:0x00007fa2a30d8c78> (NoMethodError)
```

* [x] All classes should be kept in `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

**Kindly submit another code review request once these issues have been fixed.** _Happy coding!_ 🎉

2020-02-21 07:07 UTC, suretrust commented on bin/ui.rb
> +    puts ""
* [x] No `puts/print` and `get.chomp` should be outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

2020-02-23 21:07 UTC, whiz25 requested changes
## Nice Progress 
Your code looks nice but we need to fix a few things before we can merge.
- [ ] fix this error
![24-02](https://user-images.githubusercontent.com/19773024/75120042-3f49af00-5699-11ea-8383-39d75fe2dcd3.png)
- [ ] the `main.rb` should be in the `bin` folder not the` lib`

#### Submit for another review when done with the changes

### Martin Afani

2020-02-24 12:43 UTC, fatymahmed approved these changes
## Hi @MephistoDevelop @thcdevcl, 
### Great job making the suggested changes 🎉🎉
### It's a 👍🏾 from me!
## ✔️ Approved!
Good luck with your next projects.
 _Don't forget to submit your project completion form_

2020-02-24 12:49 UTC, merged